steps:
- id: 'api-build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/k8s-app/api:${_APP_VERSION}', 'api' ]

- id: 'billing-build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/k8s-app/billing-backend:${_APP_VERSION}', 'billing-backend' ]
  waitFor: ['-']

substitutions:
  _APP_VERSION: latest

images:
- 'gcr.io/$PROJECT_ID/k8s-app/api:${_APP_VERSION}'
- 'gcr.io/$PROJECT_ID/k8s-app/billing-backend:${_APP_VERSION}'
