steps:
- id: 'backend-build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/k8s-app/billing-backend:$TAG_NAME', 'api' ]

- id: 'backend-push'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/k8s-app/billing-backend:$TAG_NAME"]
  waitFor: ['backend-build']