apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-app-config
  labels:
    app.kubernetes.io/name: k8s-app
    app.kubernetes.io/component: config
data:
  rabbitmq.host: TBD
  rabbitmq.port: "5672"
  rabbitmq.username: TBD
  rabbitmq.password: TBD

  rabbitmq.topic.name: k8s-app.reports.topic
  rabbitmq.reports.requests.queue.name: k8s-app.reports.requests.queue
  rabbitmq.reports.replies.queue.name: k8s-app.reports.replies.queue

  postgresql.host: TBD
  postgresql.port: "5432"
  postgresql.database: k8s-app
  postgresql.username: k8s-app
  postgresql.password: TBD