# This resource requires Application CRD to be installed on the K8s cluster.
# Run the following to install it:
# kubectl apply -f "https://raw.githubusercontent.com/GoogleCloudPlatform/marketplace-k8s-app-tools/master/crd/app-crd.yaml"
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: k8s-app
  labels:
    app.kubernetes.io/name: k8s-app
spec:
  descriptor:
    type: K8s Example Reports App
    version: '1.0'
    description: |-
      This application demonstrates the integrational value of GCP Marketplace.
    maintainers:
    - name: Kamil Hajduczenia
    notes: |-
      Take the next steps.
  info:
  - name: Service IP
    type: Reference
    valueFrom:
      serviceRef:
        name: reports-api
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-app
  componentKinds:
  - group: v1
    kind: Service
  - group: apps/v1
    kind: Deployment
  - group: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
