# This resource requires Application CRD to be installed on the K8s cluster.
# Run the following to install it:
# kubectl apply -f "https://raw.githubusercontent.com/GoogleCloudPlatform/marketplace-k8s-app-tools/master/crd/app-crd.yaml"
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: k8s-app
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAQAAABIkb+zAAABH0lEQVR4AezBMQgBYQCG4berGxhkYpNN2W6w3T6z1+3FHnuyx163F3sM9uUmZZONiUXq6voYDAYJjvuv/ufhRyzL8lhee+RSkym6ndEgV+qEJOhuQkiNXKgyJkYPxkyoYLQyQ87oyRMjShipSJ8jeuGBAQWM4tJlj964o4eLERwCtuiDGwIcMtZmjb64okNmfCKUwgifv2sxRyleXNq1QyOAYRgIgmkp/ReXQHHPjcZgX9Rk0RE/73Zj+5terzU2uLVeT2O7C3odNLa9vtfT2O7KXveNLW963Te2v7rX09j+ul4Hje0v6PV36QH0BwAAAGBmZnYatrX3AAAAAAAAAAAAAAAAAAAAAAAAAAABwMzMzG8VAAAAAAAAAAAzM7MfAPXLzthpPW8AAAAASUVORK5CYII=
  labels:
    app.kubernetes.io/name: k8s-app
spec:
  descriptor:
    type: K8s Example Reports App
    version: '1.0'
    description: |-
      This application demonstrates the integrational value of GCP Marketplace.
    maintainers:
    - name: Kamil Hajduczenia
    notes: |-
      Take the next steps.
  info:
  - name: Service IP
    type: Reference
    valueFrom:
      serviceRef:
        name: k8s-app-api
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-app
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: Service
  - group: apps/v1
    kind: Deployment
  - group: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
  - apiVersion: extensions/v1beta1
    kind: Ingress
